project_id = "qjuyqnkcafmetlbmcjqv"

[functions.admin-products]
verify_jwt = false

[functions.admin-video-testimonials]
verify_jwt = false

[functions.check-tracking]
verify_jwt = false

[functions.check-all-trackings]
verify_jwt = false

[functions.public-tracking-lookup]
verify_jwt = false
